### PR TITLE
Wrapped word in anchor tag and made it searchable on Google.

### PR DESCRIPTION
**Pull request by mujeeb91**

### CODE REVIEW

**Comment by hvnsweeting** [comment]
Thanks a lot :+1:

**Comment by mujeeb91** [comment]
@hvnsweeting can you please add _hacktoberfest-accepted_ label to this PR?
 For some reason it's not being added to my count.

**Comment by mujeeb91** [comment]
@hvnsweeting you have a typo in the repository topic. It should be "hacktoberfest" instead of "hactoberfest" (you're missing a k).

**Comment by hvnsweeting** [comment]
@mujeeb91 updated

**Pull request merged**
